apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-03f60cb5232683f0c, subnet-0d2099f19c54693f5
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
